support windows, use duckscript

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -3,28 +3,32 @@ reduce_output = false
 
 [tasks.9ccrs]
 description = "Check if binaries compiled by 9ccrs works as expected"
-condition = { platforms = ["linux"], fail_message = "Only Linux is supported" }
+#condition = { platforms = ["linux"], fail_message = "Only Linux is supported" }
+script_runner = "@duckscript"
 script = '''
-#!/usr/bin/env bash
-function test {
-  expected=$1
-  input=$2
+fn test
+  expected = set ${1}
+  input = set ${2}
 
-  cargo run -- "$input" > tmp.s
-  if [ ! $? ]; then
-    echo "Test failed: Failed to compile $source_code"
+  o = exec cargo run "--" ${input}
+  if not eq ${o.code} 0
+    echo "Test failed: Failed to compile ${input}"
     exit 1
-  fi
+  end
+  writefile tmp.s ${o.stdout}
 
-  gcc -o tmp tmp.s || exit 1
-  ./tmp
-  result="$?"
-
-  if [ "$result" != "$expected" ]; then
-    echo "Test failed: $expected expected but got $result"
+  o = exec gcc -o tmp.exe tmp.s
+  if not eq ${o.code} 0
+    echo "Test failed: Generated assembly is not valid"
     exit 1
-  fi
-}
+  end
+
+  o = exec ./tmp.exe
+  if not eq ${o.code} ${expected}
+    echo "Test failed: ${expected} expected, but got ${o.code}"
+    exit 1
+  end
+end
 
 test 0 0
 test 42 42
